# Generated by Django 5.0.2 on 2024-03-16 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('card', 'credit/debit'), ('cash', 'cash'), ('paypal', 'paypal')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_damage', models.BooleanField(default=False)),
                ('retail_damage', models.BooleanField(default=False)),
                ('customer_damage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('Preparing for shippment', 'Preparing for shippment'), ('SHIPPED', 'shipped'), ('OUT FOR DELIVERY', 'out for delivery'), ('DELIVERED', 'DELIVERED')], max_length=233)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_initiated', models.BooleanField(default=False)),
                ('issue_status', models.CharField(choices=[('ISSUED', 'failed'), ('PROCESSING', 'processing'), ('PASSED', 'passed'), ('FAILED', 'failed')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('returnable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_name', models.CharField(max_length=100)),
                ('accept_return', models.BooleanField(default=False)),
                ('return_to_warehouse_window', models.IntegerField(default=48, editable=False)),
                ('return_to_store_window', models.IntegerField(default=2160, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('accept_return', models.BooleanField(default=False)),
                ('return_window', models.CharField(default=720, editable=False, max_length=100)),
                ('vendor_error', models.CharField(default=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_location', models.CharField(choices=[('store', 'store'), ('online', 'online'), ('VENDOR', 'Vendor Direct')], max_length=100)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders_resolver_api_core.customer')),
                ('delivered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders_resolver_api_core.delivery')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders_resolver_api_core.product')),
                ('retail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders_resolver_api_core.retail')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders_resolver_api_core.vendor')),
            ],
        ),
    ]
