# Generated by Django 5.0.2 on 2024-04-01 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_initiated', models.BooleanField(default=False)),
                ('issue_status', models.CharField(choices=[('ISSUED', 'failed'), ('PROCESSING', 'processing'), ('PASSED', 'passed'), ('FAILED', 'failed')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('ordered', models.BooleanField(blank=True, default=False, null=True)),
                ('product', models.CharField(max_length=100)),
                ('returnable', models.BooleanField(default=False)),
                ('product_materials', models.CharField(choices=[('PLASTIC', 'plastic'), ('METAL', 'material'), ('GLASS', 'glass')], max_length=255)),
                ('product_categories', models.CharField(choices=[('HOME DECOR', 'Home Decor'), ('APPLIANCES', 'Appliances'), ('ELECTRONICS', 'Electronics'), ('ACCESSORIES', 'Accessories')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('retail_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('retail_name', models.CharField(max_length=100)),
                ('accept_return', models.BooleanField(default=False)),
                ('return_to_warehouse_window', models.IntegerField(default=48, editable=False)),
                ('return_to_store_window', models.IntegerField(default=2160, editable=False)),
                ('purchased_from', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('vendor_name', models.CharField(max_length=100)),
                ('accept_return', models.BooleanField(default=False)),
                ('return_window', models.CharField(default=720, editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('card', 'credit/debit'), ('cash', 'cash'), ('paypal', 'paypal')], max_length=100)),
                ('products_purchased', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders_resolver_api_core.product')),
                ('purchased_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders_resolver_api_core.retail')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('order_location', models.CharField(choices=[('store', 'store'), ('online', 'online'), ('VENDOR', 'Vendor Direct')], max_length=100)),
                ('delivery_status', models.CharField(choices=[('Preparing for shippment', '0001'), ('SHIPPED', '0002'), ('OUT FOR DELIVERY', '0003'), ('DELIVERED', '0004')], max_length=233)),
                ('damage', models.CharField(choices=[('CUSTOMER_DAMAGE', 'customer damage'), ('VENDOR_DAMAGE', 'vendor damage'), ('RETAIL_DAMAGE', 'retail damage'), ('NONE', None)], default=None, max_length=255)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders_resolver_api_core.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders_resolver_api_core.product')),
                ('retail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders_resolver_api_core.retail')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders_resolver_api_core.vendor')),
            ],
        ),
    ]
