# Generated by Django 5.0.2 on 2024-03-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_resolver_api_core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Damage',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='damage',
            field=models.CharField(choices=[('CUSTOMER_DAMAGE', 'customer damage'), ('VENDOR_DAMAGE', 'vendor damage'), ('RETAIL_DAMAGE', 'retail damage')], default='  ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Preparing for shippment', 'Preparing for shippment'), ('SHIPPED', 'shipped'), ('OUT FOR DELIVERY', 'out for delivery'), ('DELIVERED', 'DELIVERED')], default='random', max_length=233),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='vendor_damage', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
