# Generated by Django 5.0.2 on 2024-04-12 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_resolver_api_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='related_retails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders_resolver_api_core.retail'),
        ),
    ]
