# Generated by Django 5.0.2 on 2024-04-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_resolver_api_core', '0002_alter_order_damage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='damage',
            field=models.CharField(choices=[('1001', 'customer damage'), ('1002', 'vendor damage'), ('1003', 'retail damage'), ('0000', None)], default=False, max_length=255, null=True),
        ),
    ]
