# Generated by Django 5.0.2 on 2024-04-06 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_resolver_api_core', '0003_alter_order_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='issues',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders_resolver_api_core.issue'),
        ),
    ]
