# Generated by Django 5.0.3 on 2024-03-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_resolver_api_core", "0003_alter_order_delivery_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="payment_method",
            field=models.CharField(
                choices=[("card", "card"), ("cash", "cash"), ("paypal", "paypal")],
                max_length=100,
            ),
        ),
    ]
