# Generated by Django 5.0.2 on 2024-03-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_resolver_api_core', '0004_alter_order_customer_alter_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_error',
        ),
    ]
