# Generated by Django 5.0.3 on 2024-03-22 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders_resolver_api_core", "0004_alter_customer_payment_method"),
        ("orders_resolver_api_core", "0005_remove_vendor_vendor_error"),
    ]

    operations = []
