# Generated by Django 5.0.3 on 2024-03-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_resolver_api_core", "0006_merge_20240322_0146"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "credit/debit"),
                    ("cash", "cash"),
                    ("paypal", "paypal"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="damage",
            field=models.CharField(
                choices=[
                    ("CUSTOMER_DAMAGE", "customer damage"),
                    ("VENDOR_DAMAGE", "vendor damage"),
                    ("RETAIL_DAMAGE", "retail damage"),
                    ("NONE", "None"),
                ],
                max_length=255,
            ),
        ),
    ]
