# Generated by Django 5.0.3 on 2024-03-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders_resolver_api_core",
            "0007_alter_customer_payment_method_alter_order_damage",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
