# Generated by Django 5.0.3 on 2024-03-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_resolver_api_core", "0008_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="damage",
            field=models.CharField(
                choices=[
                    ("CUSTOMER_DAMAGE", "customer damage"),
                    ("VENDOR_DAMAGE", "vendor damage"),
                    ("RETAIL_DAMAGE", "retail damage"),
                    ("NONE", None),
                ],
                max_length=255,
            ),
        ),
    ]
